products/urls.py
from django.urls import path
from . import views
from .views import *

app_name = "products"   


urlpatterns = [

]

socialPosts/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('products/', include('products.urls')),

]

users/urls.py
from django.urls import path
from . import views
from .views import *

app_name = "users"   


urlpatterns = [
    path("", views.login_request, name="login"),
    path("register/", views.register_request, name="register"),
    # path("login/", views.login_request, name="login"),
    path("logout/", views.logout_request, name= "logout"),
    path("profile/", views.profile_request, name= "profile"),
    path("create-post/", views.create_post, name= "create_post"),
    path("all-post/", views.post_list, name= "post_list"),
    
]

products/models.py
from django.db import models

class Product(models.Model):
    name = models.CharField(max_length=100)
    weight = models.BigIntegerField(default=0)
    price = models.BigIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True, editable=False,null=True)
    updated_at = models.DateTimeField(auto_now=True, null=True, blank=True)

    def __str__(self):
        return self.name

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.base_user import BaseUserManager
from django.utils.translation import gettext_lazy as _


class UserManager(BaseUserManager):
    """
    Custom user model manager where email is the unique identifiers
    for authentication instead of usernames.
    """
    def create_user(self, email, password, **extra_fields):
        """
        Create and save a User with the given email and password.
        """
        if not email:
            raise ValueError(_('The Email must be set'))
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, email, password, **extra_fields):
        """
        Create and save a SuperUser with the given email and password.
        """
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_active', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError(_('Superuser must have is_staff=True.'))
        if extra_fields.get('is_superuser') is not True:
            raise ValueError(_('Superuser must have is_superuser=True.'))
        return self.create_user(email, password, **extra_fields)


class User(AbstractUser):
    first_name = models.CharField(max_length=100, blank=True, null=True)
    last_name = models.CharField(max_length=100, blank=True, null=True)
    email = models.EmailField(max_length=100, unique=True)
    username = models.CharField(max_length=100, unique=True)
    password = models.CharField(max_length=50)

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    objects = UserManager()

    def __str__(self):
        return self.email

class Post(models.Model):
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True, editable=False,null=True)
    updated_at = models.DateTimeField(auto_now=True, null=True, blank=True)

    def __str__(self):
        return self.user

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import User, Post


# Create your forms here.

class RegisterUserForm(UserCreationForm):

	class Meta:
		model = User
		fields = ['first_name', 'last_name', 'email', 'username']

	def save(self, commit=True):
		user = super(RegisterUserForm, self).save(commit=False)
		user.email = self.cleaned_data['email']
		user.username = self.cleaned_data['username']
		if commit:
			user.save()
		return user

class CreatePostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['text']

class LoginUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'password']

        widgets = {
            # telling Django your password field in the mode is a password input on the template
        	'password': forms.PasswordInput() 
        }

products/views.py
from django.shortcuts import render

# Create your views here.

users/views.py
from django.shortcuts import render
from django.views import generic
from .forms import RegisterUserForm, CreatePostForm, LoginUserForm
from .models import *
from django.contrib import messages
from django.shortcuts import render, HttpResponseRedirect, redirect
from django.urls import reverse
from django.contrib.auth.models import auth
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required


def register_request(request):
    if request.method == "POST":
        form = RegisterUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, "Registration successful." )
            return redirect("users:profile")
        messages.error(request, "Unsuccessful registration. Invalid information.")
    form = RegisterUserForm()
    return render (request=request, template_name="users/register.html", context={"register_form":form})


def login_request(request):
    form = LoginUserForm(request.POST)
    if request.method == "POST":
        print('post start ')
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            messages.success(request, 'Log-in Successfully')
        else:
            messages.error(request, form.errors)
    return render(request=request, template_name="users/login.html", context={"login_form":form})    


def logout_request(request):
    logout(request)
    messages.success(request, "You have successfully logged out.") 
    return redirect("users:login")

@login_required
def profile_request(request):
    return render (request=request, template_name="users/profile.html")

@login_required
def create_post(request):
    if request.method == "POST":
        form = CreatePostForm(request.POST)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.user = request.user
            new_post.save()
            messages.success(request, f'Post created Successfully')
            return redirect("users:profile")
    else:
        form = CreatePostForm()
    return render(request, 'users/create_post.html', {'form':form})


@login_required
def post_list(request):
    post = Post.objects.filter(user=request.user)
    return render(request, 'users/all_post.html', {'posts':post})

templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

	<title>socialPosts</title>
</head>
<body>


<!--Navbar-->

<nav class="navbar navbar-expand-lg navbar-dark bg-secondary">
  <a class="navbar-brand ml-4 mr-4" href="{% url 'users:register' %}"><b>Social Posts</b></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="False" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class = "navbar-nav ml-auto">
      {% if user.is_authenticated %}
      
      <li class="nav-item">
        <a class="nav-link text-warning" href="#">Welcome, {{user.username}}</a>
      </li>&emsp;
      <li>
        <a class="nav-item nav-link" href="{% url 'users:post_list' %}">All Post</a>
      </li>
      <li>
        <a class="nav-item nav-link" href="{% url 'users:create_post' %}">Create Post</a>
      </li>
      <li>
        <a class="nav-item nav-link" href="{% url 'users:profile' %}">Profile</a>
      </li>
      <li class="nav-item">
        <a class="nav-link btn btn-danger text-light" href="{% url 'users:logout' %}">Logout</a>
      </li>

      {% else %}

      <li class="nav-item">
        <a class="nav-link btn btn-success text-light" href="{% url 'users:login' %}">Login</a>
      </li>&emsp;
      <li>
        <a class="nav-link btn btn-info text-light" href="{% url 'users:register' %}">Register</a>
      </li>

      {% endif %}

    </ul>
  </div>
</nav>

<br>
{% if messages %}
  {% for message in messages %}
    <div class="alert alert-dismissible alert-{{ message.tags }}">
      <button type="button" class="close" data-dismiss="alert">
      ×
      </button>
      {{message}}
    </div>
 {% endfor %}
{% endif %}

{% block content %}  

{% endblock %}
 

<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

</body>
</html>

templates/users/all_post.html
{% extends "base.html" %}
{% block content %} 
{% load crispy_forms_tags %}  

<!--All Posts--> 
<div class="container">
        <div class="row">
          <div class="col-md-8">
            {% for post in posts %}
            <div class="card card-signin my-5">
              <div class="card-body">
                
                <a class="text-dark" href="{% url 'users:profile' %}"><b>{{ post.user.username }}</b></a>
                
                <br><small class="text-muted">Posted on {{ post.created_at }}</small>
                <br><br>
                <p class="card-text text-dark">{{ post.text }}</p>
                <br>
                <a class="text-dark" href="#"><b></b></a>
              </div>
              
              
            </div>
            {% endfor %}
           </div>
        </div>
    </div>

{% endblock %}

templates/users/create_post.html
{% extends "base.html" %}
{% block content %} 
{% load crispy_forms_tags %}  

<!--create post--> 
<br><br>
<div class="container">
    <div class="row">
      <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
        <div class="card card-signin my-5">
          <div class="card-body">
            <h5 class="card-title text-center"><b>Post</b></h5>
            <form class="form-signin" method = "POST" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="form-group"><br>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-lg btn-primary btn-block text-uppercase" type="submit">Post</button><br>
            </div>
        </form>
    </div>
    </div>
    </div>
    </div>
</div>

{% endblock content %}

templates/users/login.html
{% extends "base.html" %}
{% block content %}      
{% load crispy_forms_tags %} 

<!--Login--> 
<div class="container">
  <div class="row">
    <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
      <div class="card card-signin my-5">
        <div class="card-body">
          <h5 class="card-title text-center text-dark"><b>Login</b></h5>
          <form class="form-signin" method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
              <br />
              {{ login_form | crispy }}
            </fieldset>
            <div class="form-group">
              <button
                class="btn btn-lg btn-success btn-block text-uppercase"
                type="submit"
              >
                Login</button
              ><br /><br />
              
            </div>
            <small
              ><p class="text-center">
                Not registered yet!
                <a href="{% url 'users:register' %}"><b>Register Now!</b></a>
              </p></small
            >
          </form>
        </div>
      </div>
    </div>
  </div>
</div>


{% endblock %}

templates/users/profile.html
{% extends "base.html" %}
{% block content %} 
{% load crispy_forms_tags %}  

<!--Register--> 
<div class="container text-center">
  <br>
  <br>
  <h1>you are on profile page</h1>
  <br>
  <br>
  <br>
  <h3>{{request.user.first_name}}</h3>
  <h3>{{request.user.last_name}}</h3>
  <h3>{{request.user.username}}</h3>
  <h3>{{request.user.email}}</h3>
</div>


{% endblock %}

templates/users/register.html
{% extends "base.html" %}
{% block content %} 
{% load crispy_forms_tags %}  

<!--Register--> 
<div class="container">
  <div class="row">
    <div class="col-sm-9 col-md-9 col-lg-7 mx-auto">
      <div class="card card-signin my-5">
        <div class="card-body">
          <h5 class="card-title text-center"><b>Register</b></h5>
          <form class="form-signin" method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
              <br />
              {{ register_form | crispy}}
            </fieldset>
            <div class="form-group">
              <button
                class="btn btn-lg btn-info btn-block text-uppercase"
                type="submit"
              >
                Register</button
              ><br /><br />
            </div>
            <small
              ><p class="text-center">
                Already Registered!
                <a href="{% url 'users:login' %}"><b>Login Now!</b></a>
              </p></small
            >
          </form>
        </div>
      </div>
    </div>
  </div>
</div>


{% endblock %}